name: build jar
on:
  push:
    branches: [ "master" ]
env:
  AWS_REGION: "eu-north-1"
  SERVER_IP: ${{secrets.EC2_PUBLIC_DNS}}
  SERVER_USER: ${{secrets.EC2_USERNAME}}
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: git clone repo
      uses: actions/checkout@v2
    - name: setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        cache: gradle
    - name: build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
    - name: create RSA private key file
      env:
        PRIVATE_KEY: ${{secrets.EC2_RSA_PRIVATE_KEY}}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: SSH setup
      run: |
        mkdir ~/.ssh
        ssh-agent -a
        ssh-add private_key
        ssh-keyscan -H $SERVER_IP >> $HOME/.ssh/known_hosts
        chmod 644 $HOME/.ssh/known_hosts
  
    - name: copy jar to EC2 instance
      run: scp -o StrictHostKeyChecking=no -i private_key ./build/libs/crazycook-telegrambot-1.0-SNAPSHOT.jar $SERVER_USER@$SERVER_IP.$AWS_REGION.compute.amazonaws.com:~

  
