name: CI-CD-to-AWS
on:
  push:
    branches: [ "master" ]
env:
  AWS_REGION: "eu-north-1"
  SERVER_IP: ${{secrets.EC2_SERVER}}
  SERVER_USER: ${{secrets.EC2_USERNAME}}
  SSH_AUTH_SOCK: /tmp/ssh_agent_${{ github.sha }}.sock
  APP_PROPERTIES: ${{secrets.APPLICATION_PROPERTIES}}
  PRIVATE_KEY: ${{secrets.EC2_RSA_PRIVATE_KEY}}

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: git clone repo
      uses: actions/checkout@v2
    - name: setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        cache: gradle
    - name: Prepare application properties
      run: 
        echo "$APP_PROPERTIES" > src/main/resources/application.properties
    - name: build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
    - name: create RSA private key file
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: SSH setup
      run: |
        mkdir ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add private_key
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
  
    - name: copy jar to EC2 instance
      run: scp -i private_key ./build/libs/crazycook-telegrambot-1.0-SNAPSHOT.jar $SERVER_USER@$SERVER_IP:~
    
    - name: restart application
      run: |
        ssh -i private_key $SERVER_USER@$SERVER_IP 'bash -s' < start_crazycook.sh

