name: build jar
on:
  push:
    branches: [ "master" ]
    
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: git clone repo
      uses: actions/checkout@v2
    - name: setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: build with Gradle
      run: |
         ./gradlew wrapper --gradle-version=8.0
         ./gradlew build
